import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';

const $=s=>document.querySelector(s),container=$('#math-canvas');
let renderer;
try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:false})}catch(error){const f=$('#lab-fallback');f.hidden=false;f.querySelector('p').textContent=error.message;$('#math-loading').classList.add('done');throw error}
renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.8));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;container.appendChild(renderer.domElement);
const scene=new THREE.Scene();scene.background=new THREE.Color(0x030615);scene.fog=new THREE.FogExp2(0x030615,.027);const camera=new THREE.PerspectiveCamera(46,innerWidth/innerHeight,.1,180);camera.position.set(11,9,18);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.enablePan=false;controls.minDistance=8;controls.maxDistance=30;controls.target.set(0,2,0);
scene.add(new THREE.HemisphereLight(0x9bbdff,0x141024,1.1));const key=new THREE.DirectionalLight(0xffffff,3.2);key.position.set(6,12,8);scene.add(key);const cyan=new THREE.PointLight(0x42e8ff,45,25);cyan.position.set(-6,5,4);scene.add(cyan);
const floor=new THREE.Mesh(new THREE.PlaneGeometry(70,70),new THREE.MeshStandardMaterial({color:0x080d22,metalness:.55,roughness:.72}));floor.rotation.x=-Math.PI/2;floor.position.y=-2.2;scene.add(floor);const grid=new THREE.GridHelper(60,60,0x20426a,0x101b38);grid.position.y=-2.15;scene.add(grid);
const starsGeo=new THREE.BufferGeometry(),positions=[];for(let i=0;i<1300;i++)positions.push((Math.random()-.5)*100,Math.random()*50-4,(Math.random()-.5)*100);starsGeo.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));scene.add(new THREE.Points(starsGeo,new THREE.PointsMaterial({color:0x9cbcff,size:.055,transparent:true,opacity:.6})));

const state={mode:'number',mission:1,target:6,count:0,a:0,b:0,prediction:0,solved:false,stars:Number(localStorage.getItem('math_lab_energy')||0),combined:false};$('#star-count').textContent=state.stars;let modeGroup=new THREE.Group();scene.add(modeGroup);let clickable=[],placed=[],tweens=[],shapeData=new Map();const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();
const materials={cyan:new THREE.MeshStandardMaterial({color:0x42dff5,emissive:0x0c7f99,emissiveIntensity:1.2,metalness:.35,roughness:.25}),violet:new THREE.MeshStandardMaterial({color:0x7967ff,emissive:0x291b9e,emissiveIntensity:.9,metalness:.4,roughness:.25}),lime:new THREE.MeshStandardMaterial({color:0x6dffad,emissive:0x167b4a,emissiveIntensity:.8,metalness:.25,roughness:.28}),orange:new THREE.MeshStandardMaterial({color:0xff9158,emissive:0x8f3516,emissiveIntensity:.8,metalness:.25,roughness:.3})};
function tween(object,to,duration=650,delay=0,onDone){tweens.push({object,from:object.position.clone(),to:to.clone(),start:performance.now()+delay,duration,onDone})}
function clearMode(){scene.remove(modeGroup);modeGroup.traverse(o=>{o.geometry?.dispose()});modeGroup=new THREE.Group();scene.add(modeGroup);clickable=[];placed=[];tweens=[];shapeData.clear();state.solved=false;$('#next-mission').hidden=true;$('#primary-action').hidden=false;$('#feedback-panel').classList.remove('visible')}
function textSprite(text,color='#ffffff'){const c=document.createElement('canvas');c.width=512;c.height=128;const x=c.getContext('2d');x.font='700 52px Space Mono';x.textAlign='center';x.fillStyle=color;x.fillText(text,256,75);const s=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(c),transparent:true,depthWrite:false}));s.scale.set(5,1.25,1);return s}
function makeCell(color='cyan'){const mesh=new THREE.Mesh(new THREE.BoxGeometry(1.15,1.15,1.15,3,3,3),materials[color].clone());mesh.geometry.translate(0,0,0);const edges=new THREE.LineSegments(new THREE.EdgesGeometry(mesh.geometry),new THREE.LineBasicMaterial({color:0xffffff,transparent:true,opacity:.48}));mesh.add(edges);return mesh}
function reactor(){const g=new THREE.Group();const ring=new THREE.Mesh(new THREE.TorusGeometry(3.3,.13,12,80),new THREE.MeshBasicMaterial({color:0x42e8ff,transparent:true,opacity:.42}));ring.rotation.x=Math.PI/2;g.add(ring);for(let i=0;i<12;i++){const a=i/12*Math.PI*2,light=new THREE.Mesh(new THREE.SphereGeometry(.07,8,8),new THREE.MeshBasicMaterial({color:i%2?0x42e8ff:0x7b69ff}));light.position.set(Math.cos(a)*3.3,0,Math.sin(a)*3.3);g.add(light)}g.position.y=-1.8;modeGroup.add(g);return ring}
function updateMissionUI(kicker,title,copy,code){$('#mission-kicker').textContent=kicker;$('#mission-title').innerHTML=title;$('#mission-copy').textContent=copy;$('#mission-code').textContent=code}
function setPanels(which){$('#quantity-display').hidden=which!=='number';$('#addition-console').hidden=which!=='addition';$('#geometry-data').hidden=which!=='geometry';$('#remove-unit').hidden=which==='geometry'}
function buildNumber(){clearMode();setPanels('number');state.target=4+Math.floor(Math.random()*6);state.count=0;$('#quantity-value').textContent='0';$('#quantity-target').textContent=`TARGET / ${state.target}`;updateMissionUI('QUANTITY CONSTRUCTION',`Build a tower of <strong>${state.target}</strong>`,'Select energy cells in the field. Each unit will travel into the reactor and become part of the number.',`MISSION N-${String(state.mission).padStart(2,'0')}`);$('#primary-action').innerHTML='VERIFY STRUCTURE <span>→</span>';reactor();for(let i=0;i<10;i++){const cell=makeCell(i%2?'violet':'cyan'),a=i/10*Math.PI*2;cell.position.set(Math.cos(a)*6,Math.sin(a*.6)*1.5+1.3,Math.sin(a)*4);cell.rotation.set(a*.2,a,0);cell.userData={kind:'cell',home:cell.position.clone(),used:false};modeGroup.add(cell);clickable.push(cell)}controls.target.set(0,1,0)}
function addCell(cell){if(cell.userData.used||state.count>=10)return;cell.userData.used=true;placed.push(cell);const level=state.count++;tween(cell,new THREE.Vector3(0,-1.15+level*1.22,0),520);cell.rotation.set(0,0,0);$('#quantity-value').textContent=state.count;cell.material.emissiveIntensity=1.8}
function removeCell(){if(state.mode==='number'&&placed.length){const cell=placed.pop();state.count--;tween(cell,cell.userData.home,480,0,()=>cell.userData.used=false);$('#quantity-value').textContent=state.count}else if(state.mode==='addition'&&state.prediction>0){state.prediction--;$('#answer-value').textContent=state.prediction}}
function buildAddition(){clearMode();setPanels('addition');state.a=2+Math.floor(Math.random()*4);state.b=1+Math.floor(Math.random()*4);state.prediction=0;state.combined=false;$('#answer-value').textContent='0';updateMissionUI('GROUP COMBINATION',`Dock <strong>${state.a}</strong> and <strong>${state.b}</strong>`,'Study both formations. Set your prediction, then merge them into one structure.',`MISSION A-${String(state.mission).padStart(2,'0')}`);$('#primary-action').innerHTML='MERGE GROUPS <span>→</span>';reactor();for(let i=0;i<state.a;i++){const c=makeCell('cyan');c.position.set(-5+(i%3)*1.35,-.7+Math.floor(i/3)*1.35,0);c.userData={group:'a'};modeGroup.add(c);placed.push(c)}for(let i=0;i<state.b;i++){const c=makeCell('orange');c.position.set(3+(i%3)*1.35,-.7+Math.floor(i/3)*1.35,0);c.userData={group:'b'};modeGroup.add(c);placed.push(c)}const plus=textSprite('+','#48e8ff');plus.position.set(0,1,0);modeGroup.add(plus);controls.target.set(0,1,0)}
function mergeAddition(){if(state.combined)return verifyAddition();state.combined=true;placed.forEach((cell,i)=>tween(cell,new THREE.Vector3(0,-1.15+i*1.22,0),700,i*65));$('#primary-action').innerHTML='CHECK PREDICTION <span>→</span>';showFeedback('Groups are docking. Count every unit in the new structure.')}
const SHAPES=[{name:'Cube',faces:6,edges:12,vertices:8,clue:'Find the solid with 6 equal square faces.',geo:()=>new THREE.BoxGeometry(2.7,2.7,2.7),color:'cyan'},{name:'Triangular Pyramid',faces:4,edges:6,vertices:4,clue:'Find the solid with 4 triangular faces.',geo:()=>new THREE.TetrahedronGeometry(2.25),color:'violet'},{name:'Cylinder',faces:3,edges:2,vertices:0,clue:'Find the solid with two circular ends and one curved surface.',geo:()=>new THREE.CylinderGeometry(1.6,1.6,3.2,48),color:'orange'}];
function buildGeometry(){clearMode();setPanels('geometry');const target=SHAPES[Math.floor(Math.random()*SHAPES.length)];state.shapeTarget=target.name;updateMissionUI('SPATIAL REASONING',`Identify the <strong>mystery solid</strong>`,target.clue,`MISSION G-${String(state.mission).padStart(2,'0')}`);$('#primary-action').hidden=true;SHAPES.forEach((data,i)=>{const mesh=new THREE.Mesh(data.geo(),materials[data.color].clone());mesh.position.set((i-1)*5,1,0);mesh.rotation.set(.35,i*.4,.15);const wire=new THREE.LineSegments(new THREE.EdgesGeometry(mesh.geometry),new THREE.LineBasicMaterial({color:0xffffff,transparent:true,opacity:.65}));mesh.add(wire);modeGroup.add(mesh);clickable.push(mesh);shapeData.set(mesh,data)});controls.target.set(0,1,0);$('#shape-name').textContent='Select a solid';['#shape-faces','#shape-edges','#shape-vertices'].forEach(id=>$(id).textContent='—')}
function inspectShape(mesh){const d=shapeData.get(mesh);$('#shape-name').textContent=d.name;$('#shape-faces').textContent=d.faces;$('#shape-edges').textContent=d.edges;$('#shape-vertices').textContent=d.vertices;mesh.scale.set(1.15,1.15,1.15);setTimeout(()=>mesh.scale.set(1,1,1),350);if(d.name===state.shapeTarget)solve(`Scan confirmed: ${d.name}. Rotate it and inspect every surface.`);else showFeedback(`That is a ${d.name}. Compare its surfaces with the mission clue.`)}
function verifyNumber(){if(state.count===state.target)solve(`${state.count} units confirmed. You constructed the quantity.`);else showFeedback(state.count<state.target?`The reactor needs ${state.target-state.count} more unit${state.target-state.count===1?'':'s'}.`:`Release ${state.count-state.target} unit${state.count-state.target===1?'':'s'} to match the target.`)}
function verifyAddition(){const total=state.a+state.b;if(state.prediction===total)solve(`${state.a} plus ${state.b} forms ${total}. The docking calculation is stable.`);else showFeedback(`The structure has ${total} units. Adjust your prediction and scan again.`)}
function solve(message){if(state.solved)return;state.solved=true;state.stars+=10;localStorage.setItem('math_lab_energy',state.stars);$('#star-count').textContent=state.stars;showFeedback(message);$('#primary-action').hidden=true;$('#next-mission').hidden=false;placed.forEach((m,i)=>{setTimeout(()=>{m.material.emissiveIntensity=2.8;setTimeout(()=>m.material.emissiveIntensity=1.1,500)},i*70)})}
function showFeedback(message){$('#feedback-text').textContent=message;$('#feedback-panel').classList.add('visible');setTimeout(()=>$('#feedback-panel').classList.remove('visible'),3600)}
function build(){({number:buildNumber,addition:buildAddition,geometry:buildGeometry})[state.mode]()}
renderer.domElement.addEventListener('pointerup',e=>{const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);raycaster.setFromCamera(pointer,camera);const hit=raycaster.intersectObjects(clickable,false)[0];if(!hit)return;if(state.mode==='number')addCell(hit.object);if(state.mode==='geometry')inspectShape(hit.object)});
document.querySelectorAll('.mode-button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.mode-button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.mode=b.dataset.mode;state.mission=1;build()}));$('#remove-unit').addEventListener('click',removeCell);$('#answer-down').addEventListener('click',()=>{state.prediction=Math.max(0,state.prediction-1);$('#answer-value').textContent=state.prediction});$('#answer-up').addEventListener('click',()=>{state.prediction=Math.min(20,state.prediction+1);$('#answer-value').textContent=state.prediction});$('#primary-action').addEventListener('click',()=>state.mode==='number'?verifyNumber():mergeAddition());$('#next-mission').addEventListener('click',()=>{state.mission++;build()});$('#speak-mission').addEventListener('click',()=>{if('speechSynthesis'in window){speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(`${$('#mission-title').textContent}. ${$('#mission-copy').textContent}`))}});
function animate(now){for(let i=tweens.length-1;i>=0;i--){const t=tweens[i];if(now<t.start)continue;const p=Math.min(1,(now-t.start)/t.duration),ease=1-Math.pow(1-p,3);t.object.position.lerpVectors(t.from,t.to,ease);if(p===1){t.onDone?.();tweens.splice(i,1)}}if(state.mode==='geometry')clickable.forEach((m,i)=>{m.rotation.y+=.0025+i*.0006});else clickable.filter(c=>!c.userData.used).forEach((m,i)=>{m.position.y+=Math.sin(now*.0018+i)*.0018;m.rotation.y+=.004});controls.update();renderer.render(scene,camera);requestAnimationFrame(animate)}
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});build();setTimeout(()=>$('#math-loading').classList.add('done'),850);requestAnimationFrame(animate);
