import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { CSS2DRenderer, CSS2DObject } from 'three/addons/renderers/CSS2DRenderer.js';

const $ = (selector) => document.querySelector(selector);
const container = $('#space-canvas');

const PLANETS = [
  { name:'Mercury', color:'#aaa8a1', accent:'#6e6d69', radius:.48, orbit:7, speed:1.61, year:'88 days', moons:'0', temp:'167°C', kind:'THE SWIFT ROCK', fact:'Mercury races around the Sun faster than any other planet, but turns very slowly.', tilt:.03 },
  { name:'Venus', color:'#dfaa58', accent:'#9b5f29', radius:.76, orbit:10, speed:1.18, year:'225 days', moons:'0', temp:'464°C', kind:'THE CLOUD-WRAPPED WORLD', fact:'Venus is the hottest planet. Its thick atmosphere traps heat like a giant blanket.', tilt:.05 },
  { name:'Earth', color:'#2471a8', accent:'#42a66b', radius:.82, orbit:13.5, speed:1, year:'365 days', moons:'1', temp:'15°C', kind:'OUR OCEAN WORLD', fact:'Earth is the only known world with oceans of liquid water and living things.', tilt:.41 },
  { name:'Mars', color:'#a94726', accent:'#e17b46', radius:.62, orbit:17.5, speed:.81, year:'687 days', moons:'2', temp:'−65°C', kind:'THE RUSTY WORLD', fact:'Mars has Olympus Mons—the tallest volcano known in our solar system.', tilt:.44 },
  { name:'Jupiter', color:'#c29568', accent:'#eee0c8', radius:1.95, orbit:24, speed:.44, year:'11.9 years', moons:'95', temp:'−110°C', kind:'THE GAS GIANT', fact:'Jupiter is more massive than every other planet combined and has a centuries-old storm.', tilt:.05 },
  { name:'Saturn', color:'#d9bc7c', accent:'#f4dfa7', radius:1.65, orbit:31, speed:.32, year:'29.5 years', moons:'146+', temp:'−140°C', kind:'THE RINGED GIANT', fact:'Saturn’s rings are made from countless pieces of ice and rock, from dust to mountain size.', tilt:.47, rings:true },
  { name:'Uranus', color:'#77cfda', accent:'#bcecf0', radius:1.18, orbit:38, speed:.23, year:'84 years', moons:'28', temp:'−195°C', kind:'THE SIDEWAYS WORLD', fact:'Uranus rotates almost completely on its side, likely after a huge collision long ago.', tilt:1.71 },
  { name:'Neptune', color:'#315be1', accent:'#79a2ff', radius:1.15, orbit:45, speed:.18, year:'165 years', moons:'16', temp:'−200°C', kind:'THE WINDY BLUE WORLD', fact:'Neptune has the fastest winds in the solar system—faster than the speed of sound.', tilt:.49 }
];
const MISSIONS = [
  { target:'Mars', title:'Find the rusty world', clue:'I am covered in iron-rich dust and home to the tallest volcano we know.' },
  { target:'Saturn', title:'Find the icy rings', clue:'Millions of pieces of ice and rock make a spectacular disc around me.' },
  { target:'Jupiter', title:'Find the largest planet', clue:'I could fit every other planet inside me, and my giant storm has raged for centuries.' },
  { target:'Uranus', title:'Find the sideways world', clue:'Unlike the others, I roll around the Sun almost completely on my side.' }
];

let renderer;
try { renderer = new THREE.WebGLRenderer({ antialias:true, powerPreference:'high-performance', alpha:false }); }
catch (error) { $('#webgl-fallback').hidden=false; $('#loading-screen').classList.add('done'); throw error; }
renderer.setPixelRatio(Math.min(devicePixelRatio, 1.8)); renderer.setSize(innerWidth, innerHeight); renderer.outputColorSpace=THREE.SRGBColorSpace; renderer.toneMapping=THREE.ACESFilmicToneMapping; renderer.toneMappingExposure=1.08; container.appendChild(renderer.domElement);
const labelRenderer = new CSS2DRenderer(); labelRenderer.setSize(innerWidth,innerHeight); labelRenderer.domElement.style.cssText='position:absolute;inset:0;pointer-events:none'; container.appendChild(labelRenderer.domElement);
const scene = new THREE.Scene(); scene.background = new THREE.Color(0x01030a); scene.fog = new THREE.FogExp2(0x01030a,.006);
const camera = new THREE.PerspectiveCamera(48,innerWidth/innerHeight,.1,400); camera.position.set(0,24,56);
const controls = new OrbitControls(camera,renderer.domElement); controls.enableDamping=true; controls.dampingFactor=.05; controls.minDistance=4; controls.maxDistance=105; controls.enablePan=false; controls.target.set(0,0,0); controls.autoRotate=true; controls.autoRotateSpeed=.18;
scene.add(new THREE.AmbientLight(0x8291bb,.14)); const sunLight=new THREE.PointLight(0xfff2d2,260,150,1.7); scene.add(sunLight);

function seededNoise(x,y,seed){const value=Math.sin(x*12.9898+y*78.233+seed*91.1)*43758.5453;return value-Math.floor(value)}
function makePlanetTexture(base,accent,seed,striped=false){const canvas=document.createElement('canvas');canvas.width=512;canvas.height=256;const ctx=canvas.getContext('2d');const grad=ctx.createLinearGradient(0,0,0,256);grad.addColorStop(0,accent);grad.addColorStop(.5,base);grad.addColorStop(1,accent);ctx.fillStyle=grad;ctx.fillRect(0,0,512,256);ctx.globalCompositeOperation='soft-light';for(let y=0;y<256;y+=striped?5:12){const n=seededNoise(2,y,seed);ctx.fillStyle=`rgba(${n>0.5?255:0},${n>0.5?245:20},${n>0.5?225:35},${striped?.08:.12})`;ctx.fillRect(0,y,512,striped?2+n*5:4+n*10)}for(let i=0;i<55;i++){const x=seededNoise(i,3,seed)*512,y=seededNoise(i,7,seed)*256,r=2+seededNoise(i,11,seed)*20;ctx.fillStyle=`rgba(255,255,255,${.02+seededNoise(i,9,seed)*.09})`;ctx.beginPath();ctx.ellipse(x,y,r*2,r,0,0,Math.PI*2);ctx.fill()}const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;texture.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());return texture}
function glowTexture(){const c=document.createElement('canvas');c.width=c.height=256;const x=c.getContext('2d'),g=x.createRadialGradient(128,128,8,128,128,128);g.addColorStop(0,'rgba(255,248,200,1)');g.addColorStop(.2,'rgba(255,169,52,.7)');g.addColorStop(1,'rgba(255,80,0,0)');x.fillStyle=g;x.fillRect(0,0,256,256);return new THREE.CanvasTexture(c)}

const universe=new THREE.Group();scene.add(universe);
const starPositions=[];for(let i=0;i<5200;i++){const r=70+Math.random()*180,theta=Math.random()*Math.PI*2,phi=Math.acos(2*Math.random()-1);starPositions.push(r*Math.sin(phi)*Math.cos(theta),r*Math.cos(phi),r*Math.sin(phi)*Math.sin(theta))}const starGeo=new THREE.BufferGeometry();starGeo.setAttribute('position',new THREE.Float32BufferAttribute(starPositions,3));const stars=new THREE.Points(starGeo,new THREE.PointsMaterial({color:0xcbd7ff,size:.16,sizeAttenuation:true,transparent:true,opacity:.82}));scene.add(stars);
const sun=new THREE.Mesh(new THREE.SphereGeometry(3.25,64,64),new THREE.MeshBasicMaterial({map:makePlanetTexture('#ff9d1e','#fff0a2',99,true)}));sun.name='Sun';universe.add(sun);const glow=new THREE.Sprite(new THREE.SpriteMaterial({map:glowTexture(),transparent:true,blending:THREE.AdditiveBlending,depthWrite:false}));glow.scale.set(14,14,1);sun.add(glow);
const planets=[];const clickable=[];
PLANETS.forEach((data,index)=>{const pivot=new THREE.Group();universe.add(pivot);pivot.rotation.y=index*.78;const path=new THREE.LineLoop(new THREE.BufferGeometry().setFromPoints(Array.from({length:180},(_,i)=>{const a=i/180*Math.PI*2;return new THREE.Vector3(Math.cos(a)*data.orbit,0,Math.sin(a)*data.orbit)})),new THREE.LineBasicMaterial({color:0x63709a,transparent:true,opacity:.18}));universe.add(path);const group=new THREE.Group();group.position.x=data.orbit;pivot.add(group);const material=new THREE.MeshStandardMaterial({map:makePlanetTexture(data.color,data.accent,index+2,data.radius>1.4),roughness:.82,metalness:0});const mesh=new THREE.Mesh(new THREE.SphereGeometry(data.radius,48,32),material);mesh.rotation.z=data.tilt;mesh.userData.planet=data;group.add(mesh);clickable.push(mesh);if(data.rings){const rings=new THREE.Mesh(new THREE.RingGeometry(2.05,3.15,96),new THREE.MeshStandardMaterial({color:0xcbb98a,side:THREE.DoubleSide,transparent:true,opacity:.72,roughness:.8}));rings.rotation.x=Math.PI/2;mesh.add(rings)}if(data.name==='Earth'){const moonPivot=new THREE.Group();group.add(moonPivot);const moon=new THREE.Mesh(new THREE.SphereGeometry(.18,24,16),new THREE.MeshStandardMaterial({color:0xbdbdb7,roughness:1}));moon.position.x=1.45;moonPivot.add(moon);data.moonPivot=moonPivot}const label=document.createElement('div');label.className='planet-label';label.textContent=data.name.toUpperCase();const labelObject=new CSS2DObject(label);labelObject.position.set(0,data.radius+1,0);group.add(labelObject);data.label=label;planets.push({data,pivot,group,mesh});});

const dock=$('#planet-dock');PLANETS.forEach((p,i)=>{const button=document.createElement('button');button.type='button';button.setAttribute('aria-label',`Fly to ${p.name}`);button.style.setProperty('--color',p.color);button.style.setProperty('--size',`${Math.min(21,9+p.radius*6)}px`);button.innerHTML=`<i></i><span>${p.name.toUpperCase()}</span>`;button.addEventListener('click',()=>selectPlanet(i));dock.appendChild(button)});
let launched=false,paused=false,timeScale=1,mission=0,selected=null,flight=null,last=performance.now();
function updateMission(){const m=MISSIONS[mission];$('#mission-index').textContent=String(mission+1).padStart(2,'0');$('#mission-title').textContent=m.title;$('#mission-clue').textContent=m.clue;$('#mission-score').textContent=`${mission} / ${MISSIONS.length}`;$('#mission-dots').style.setProperty('--progress',`${mission/MISSIONS.length*100}%`)}
function showPlanet(data,index){$('#planet-order').textContent=`PLANET ${String(index+1).padStart(2,'0')}`;$('#planet-name').textContent=data.name;$('#planet-kind').textContent=data.kind;$('#planet-year').textContent=data.year;$('#planet-moons').textContent=data.moons;$('#planet-temp').textContent=data.temp;$('#planet-fact').textContent=data.fact;$('#planet-panel').classList.add('visible');dock.querySelectorAll('button').forEach((b,i)=>b.classList.toggle('active',i===index));if(launched&&mission<MISSIONS.length){if(data.name===MISSIONS[mission].target){$('#mission-title').textContent='Discovery confirmed';$('#mission-clue').textContent=`Excellent navigation. ${data.fact}`;mission++;$('#mission-score').textContent=`${mission} / ${MISSIONS.length}`;setTimeout(()=>{if(mission<MISSIONS.length)updateMission();else{$('#mission-type').textContent='EXPEDITION COMPLETE';$('#mission-title').textContent='Solar System Navigator';$('#mission-clue').textContent='You followed evidence across the solar system. Every planet is now open for free exploration.'}},2600)}else{$('#mission-clue').textContent=`Good scan—but this is ${data.name}. Look again: ${MISSIONS[mission].clue}`}}}
function selectPlanet(index,close=false){const entry=planets[index];selected=index;showPlanet(entry.data,index);const world=new THREE.Vector3();entry.mesh.getWorldPosition(world);const direction=world.clone().normalize();const offset=new THREE.Vector3(direction.x*(entry.data.radius*5+3),entry.data.radius*2.5+1,direction.z*(entry.data.radius*5+3));startFlight(world.clone().add(offset),world,close?1800:1300)}
function startFlight(to,target,duration=1300){flight={from:camera.position.clone(),to,targetFrom:controls.target.clone(),target,start:performance.now(),duration};controls.autoRotate=false}
function solarView(){selected=null;$('#planet-panel').classList.remove('visible');dock.querySelectorAll('button').forEach(b=>b.classList.remove('active'));startFlight(new THREE.Vector3(0,24,56),new THREE.Vector3(0,0,0),1600);controls.autoRotate=true}
const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();renderer.domElement.addEventListener('pointerup',(event)=>{if(!launched)return;const rect=renderer.domElement.getBoundingClientRect();pointer.x=(event.clientX-rect.left)/rect.width*2-1;pointer.y=-(event.clientY-rect.top)/rect.height*2+1;raycaster.setFromCamera(pointer,camera);const hit=raycaster.intersectObjects(clickable,false)[0];if(hit){const index=PLANETS.indexOf(hit.object.userData.planet);selectPlanet(index)}});
$('#launch-button').addEventListener('click',()=>{launched=true;$('#intro-overlay').classList.add('hidden');$('#mission-console').classList.add('visible');controls.autoRotate=false;updateMission();startFlight(new THREE.Vector3(0,18,48),new THREE.Vector3(0,0,0),1800)});$('#close-panel').addEventListener('click',()=>$('#planet-panel').classList.remove('visible'));$('#planet-visit').addEventListener('click',()=>{if(selected!==null)selectPlanet(selected,true)});$('#reset-view').addEventListener('click',solarView);
const speeds=[0,.2,.6,1,2.4];$('#time-speed').addEventListener('input',e=>{timeScale=speeds[Number(e.target.value)];paused=timeScale===0;$('#time-output').textContent=timeScale===0?'0×':`${timeScale}×`;$('#pause-time').textContent=paused?'▶':'Ⅱ'});$('#pause-time').addEventListener('click',()=>{paused=!paused;$('#pause-time').textContent=paused?'▶':'Ⅱ'});
let audioCtx,hum;$('#sound-toggle').addEventListener('click',()=>{if(!audioCtx){const AudioEngine=window.AudioContext||window.webkitAudioContext;audioCtx=new AudioEngine();const osc=audioCtx.createOscillator(),gain=audioCtx.createGain();osc.type='sine';osc.frequency.value=52;gain.gain.value=.018;osc.connect(gain).connect(audioCtx.destination);osc.start();hum={osc,gain};$('#sound-toggle b').textContent='ON'}else{const on=hum.gain.gain.value>0;hum.gain.gain.setTargetAtTime(on?0:.018,audioCtx.currentTime,.1);$('#sound-toggle b').textContent=on?'OFF':'ON'}});
function animate(now){const dt=Math.min(.04,(now-last)/1000);last=now;if(!paused){planets.forEach((p,i)=>{p.pivot.rotation.y+=dt*.14*p.data.speed*timeScale;p.mesh.rotation.y+=dt*(.12+i*.01)*timeScale;if(p.data.moonPivot)p.data.moonPivot.rotation.y+=dt*1.2*timeScale});sun.rotation.y+=dt*.025*timeScale;stars.rotation.y+=dt*.002}if(flight){const t=Math.min(1,(now-flight.start)/flight.duration),ease=t<.5?4*t*t*t:1-Math.pow(-2*t+2,3)/2;camera.position.lerpVectors(flight.from,flight.to,ease);controls.target.lerpVectors(flight.targetFrom,flight.target,ease);if(t===1)flight=null}controls.update();renderer.render(scene,camera);labelRenderer.render(scene,camera);requestAnimationFrame(animate)}
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);labelRenderer.setSize(innerWidth,innerHeight)});
updateMission();setTimeout(()=>{$('#load-progress').style.width='180px'},100);setTimeout(()=>{$('#loading-screen').classList.add('done')},900);requestAnimationFrame(animate);
